Готова первая проектная работа
MargoReal/s-chistogo-lista pull request #3
Opened 2024-02-25 14:21 UTC by MargoReal

Отправлю на ревью

2024-02-25 15:18 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа!

_Что понравилось:_

- Хорошая структура HTML
- Хорошее форматирование документа
- хорошие стили
- используется семантика
- Используются списки


_Что необходимо исправить:_

- **Все комментарии  с пометкой "Нужно исправить" в коде**

- https://disk.yandex.ru/i/rpWDOX2_JJwUIg
  - Название шрифта, которое содержит пробелы нужно всегда брать в кавычки, или браузер может не понять это значение
  - Нужно указать альтернативный шрифт (тип засечек для выбора шрифта браузера без засечек по-умолчанию (для шрифта Inter)значение sans-serif и **для шрифта с засечками(EB Garamond) тип serif**) для каждого значения font-family в проекте, кроме файла подключения шрифтов, где это св-во задаёт только название подключаемого шрифта
    - https://doka.guide/css/font-family

- Несоответствия макету:
    - https://disk.yandex.ru/i/2SVjTbVlKrh0Xw нет отступа между ссылками, добавьте его через flex gap
    -  https://disk.yandex.ru/i/PGrYRQrxtIVVSg // https://disk.yandex.ru/i/vVR0FRWBLhTz1Q высота строки




_Что можно улучшить:_

- Все комментарии "Можно лучше"

- Селекторы в файле стилей должны располагаться в порядке их появления в html

- В любом месте в файлах CSS в проекте(кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта), где указано свойство  `font-family`  помимо основного шрифта так же должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинами основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно.  Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек. Пример ` font-family: Inter, Arial, sans-serif; ` 

- Желательно использовать все классы по БЭМ. 
  - https://ru.bem.info/methodology/quick-start/
  - Проверить ошибки БЭМ можно на  https://nglazov.github.io/bem-validator-page/
  - струтуру можно проверить на https://yoksel.github.io/html-tree/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 


**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-02-25 15:18 UTC, Avaakum commented on styles/style.css
> +    height: 62px;
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding) и внешние (margin) отступы для соответствия макету.

2024-02-25 15:18 UTC, Avaakum commented on styles/style.css
> +    height: 559px;
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding) и внешние (margin) отступы для соответствия макету.

2024-02-25 15:18 UTC, Avaakum commented on styles/style.css
> +    height: 368px;
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding) и внешние (margin) отступы для соответствия макету.

2024-02-25 15:18 UTC, Avaakum commented on styles/style.css
> +    height: 495px;
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding) и внешние (margin) отступы для соответствия макету.

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +    <link rel="stylesheet" href="./styles/style.css" />
---

**Отлично:**

Правильный порядок подключения стилей. Шрифты должны быть подключены первыми, потом общие стили(сброс), потом кастомные. При таком порядке подключении шрифты могут быть использованы в двух последующих файлах.  А так же сброс стилей должен быть до подключения своих стилей из-за специфики CSS, чтобы `global.css` не переопределил никаких наших стилей.

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +      <a class="header__logo">
---

**Отлично:**

Логотип должен быть ссылкой без атрибута href(что бы по ссылке не было перехода)

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +          <p class="intro__date">
Лишний элемент, присвойте класс сразу для тега time

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +            <time datetime="2022-06-05">05.06.2022 г.</time>
---

**Отлично:**

Отличная семантика

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +          <p class="intro__main-text_two">
Параграфы нужно объединить в общий контейнер по смыслу "текст". А так же отступ между параграфами можно задать через flex gap. Параграфов может быть любое количество и отступы должны работать без доп. классов. Различающиеся классы для параграфов нужно удалить

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +        <div>
Добасьте класс для див, и присвойте через него стили и отступы для параграфов, их может любое количество

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +        <div>
Лишний див

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +            <li class="content-section__list-item">
---

**Отлично:**

Отлично, использован список для повторяющихся элементов

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +        <div class="cards-list">
Лишний див, присвойте класс сразу для ul

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +                  <a class="card__author-photo">
Лишний тег, тут не нужно оборачивать фото

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +                  <a class="card__author-photo">
Отлично, использован список для повторяющихся элементов

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +                  <h2 class="card__title_dark">Начать любыми словами</h2>
- Уровень заголовка не соответствует структуре страницы. Тут  и далее в секции будут h3 по структуре

---


- Про заголовки и подзаголовки на примере другой страницы с секциями, хэдером, и футером: у нас есть **один заголовок h1 на странице**, в каждой секции есть свой заголовок h2, если там есть другие элементы с заголовками ниже по иерархии, то они будут h3. Если например в секции был бы заголовок h2 и подзаголовок h3, то элементы с заголовками ниже по иерархии в этой же секции были бы уже h4.

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +                  <h3 class="card__author-name">Алексей Поляринов</h3>
Это не заголовок, используйте тег p

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +                  <h3 class="card__author-name">Иван Бунин</h3>
Это не заголовок, используйте тег p

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +                  <h2 class="card__title_dark">Сделать из задачи рутину</h2>
Тут  будет h3

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +          <li class="footer__links__menu">
---

**Отлично:**

Отличная семантика и структура

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +        <ul class="footer__links">
---

**Можно лучше:**

Можно использовать для обертки списка ссылок тег `<nav>`, можно даже без класса, только для семантики.
Этим элементом принято выделять список из ссылок, отвечающий за навигацию по сайту и не только. Добавление этого элемента улучшает восприятие вашей верстки поисковыми машинами, а так же скринридерами. 
Можно использовать несколько тегов `nav` в проекте.

https://doka.guide/html/nav/#alyona-batickaya-sovetuet

2024-02-25 15:18 UTC, Avaakum commented on index.html
> +    </main>
- Семантический тег `<main>` мы используем для выделения основного содержимого страницы. Это то, что между `header` и `footer`

2024-02-25 21:05 UTC, MargoReal commented on index.html
> +          <p class="intro__date">
@Avaakum  Привет) А подскажи про какой лишний элемент идет речь?

2024-02-25 21:13 UTC, MargoReal commented on fonts/fonts.css
> +      url(./interbold.woff2)
@Avaakum  Привет)

Вижу что поключен вот этот шрифт  

@font-face {
    font-family: 'Inter';
    src:
      url(./interbold.woff2)
        format('woff2'),
      url(./interbold.woff)
        format('woff'),
      url(./interbold.ttf)
        format('truetype');
    font-weight: 700;
    font-display: swap;
}

вроде бы Interbold и идет с font weight 700, а не 400, как было указано в рекомендациях по верстке:

![image](https://github.com/MargoReal/s-chistogo-lista/assets/160176783/b78a1408-9daf-4afa-ae0c-129ad9276370)

Разве нет?

2024-02-27 12:34 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 

---

_Что необходимо исправить:_


- https://disk.yandex.ru/i/_b8INjjbMhkjBg Inter - это шрифт без засечек, альтернатива для него sans-serif(тип serif в конце нужно удалить), "EB Garamond" шрифт с засечками, для него должна быть альтернатива serif(остальные значения нужно удалить). Альтернативный веб-безопастный шрифт для "EB Garamond" так же  должен быть шрифтом с засечками, смотрите веб-безопасные альтернативы в соответствии с типами шрифтов на   https://www.cssfontstack.com/
   -  https://doka.guide/css/font-family




---




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 


Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2024-02-27 13:31 UTC, merged